:sparkles: (feat): add subraces class
KendoSensei/AP5_dungeons-dragons pull request #10
Opened 2024-10-11 17:58 UTC by KendoSensei

2024-10-11 22:25 UTC, liestig requested changes

2024-10-11 22:25 UTC, liestig commented on src/entities/subraces.entity.ts
Ta classe elle doit extends Races vu que c'est un héritage

2024-10-12 18:13 UTC, erwanbslk commented on src/entities/subraces.entity.ts
c'est fait mais je sais pas pourquoi y'a des conflits dans la PR

2024-10-13 14:20 UTC, liestig approved these changes

2024-10-13 14:20 UTC, merged